# Generated by Django 5.1.1 on 2025-11-28 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_user_is_active_user_is_email_verified_user_is_staff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('revenuecat_entitlement_id', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'entitlement_table',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('monthly', 'Monthly Premium'), ('yearly', 'Yearly Premium'), ('lifetime', 'Lifetime Premium')], max_length=20, unique=True)),
                ('revenuecat_product_id', models.CharField(help_text='Product ID in RevenueCat', max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('unlimited_appointments', models.BooleanField(default=False)),
                ('premium_therapists', models.BooleanField(default=False)),
                ('unlimited_chat', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('exclusive_content', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'subscription_plan_table',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenuecat_app_user_id', models.CharField(help_text='RevenueCat App User ID', max_length=255, unique=True)),
                ('revenuecat_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('grace_period', 'Grace Period'), ('paused', 'Paused'), ('trial', 'Trial')], default='expired', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('original_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribe_detected_at', models.DateTimeField(blank=True, null=True)),
                ('billing_issue_detected_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.CharField(blank=True, help_text='app_store, play_store, stripe, etc.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_subscription_table',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('INITIAL_PURCHASE', 'Initial Purchase'), ('RENEWAL', 'Renewal'), ('CANCELLATION', 'Cancellation'), ('UNCANCELLATION', 'Uncancellation'), ('EXPIRATION', 'Expiration'), ('BILLING_ISSUE', 'Billing Issue'), ('PRODUCT_CHANGE', 'Product Change'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund')], max_length=50)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('original_transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.CharField(max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='my_app.usersubscription')),
            ],
            options={
                'db_table': 'subscription_transaction_table',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entitlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.entitlement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_entitlement_table',
                'unique_together': {('user', 'entitlement')},
            },
        ),
    ]
