# Generated by Django 5.1.1 on 2024-11-04 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_chatmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterModelTable(
            name='chatmessage',
            table=None,
        ),
    ]
